/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRRStablecoin } from "./IRRStablecoin";
export type { IRedemptionService } from "./IRedemptionService";
