/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface SocialRecoveryWalletInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confirmRecovery"
      | "confirmationCount"
      | "confirmedGuardians"
      | "guardians"
      | "newOwnerCandidate"
      | "nominateNewOwner"
      | "owner"
      | "renounceOwnership"
      | "replaceGuardian"
      | "requiredConfirmations"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "RecoveryConfirmation"
      | "RecoveryExecuted"
      | "RecoveryNomination"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confirmRecovery",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmationCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "confirmedGuardians",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "guardians",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "newOwnerCandidate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nominateNewOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "replaceGuardian",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requiredConfirmations",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "confirmRecovery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmedGuardians",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "guardians", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "newOwnerCandidate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nominateNewOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "replaceGuardian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requiredConfirmations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecoveryConfirmationEvent {
  export type InputTuple = [guardian: AddressLike];
  export type OutputTuple = [guardian: string];
  export interface OutputObject {
    guardian: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecoveryExecutedEvent {
  export type InputTuple = [oldOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [oldOwner: string, newOwner: string];
  export interface OutputObject {
    oldOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecoveryNominationEvent {
  export type InputTuple = [candidate: AddressLike];
  export type OutputTuple = [candidate: string];
  export interface OutputObject {
    candidate: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SocialRecoveryWallet extends BaseContract {
  connect(runner?: ContractRunner | null): SocialRecoveryWallet;
  waitForDeployment(): Promise<this>;

  interface: SocialRecoveryWalletInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confirmRecovery: TypedContractMethod<
    [_candidate: AddressLike],
    [void],
    "nonpayable"
  >;

  confirmationCount: TypedContractMethod<[], [bigint], "view">;

  confirmedGuardians: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  guardians: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  newOwnerCandidate: TypedContractMethod<[], [string], "view">;

  nominateNewOwner: TypedContractMethod<
    [_newOwnerCandidate: AddressLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  replaceGuardian: TypedContractMethod<
    [_oldGuardian: AddressLike, _newGuardian: AddressLike],
    [void],
    "nonpayable"
  >;

  requiredConfirmations: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confirmRecovery"
  ): TypedContractMethod<[_candidate: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confirmationCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "confirmedGuardians"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "guardians"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "newOwnerCandidate"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "nominateNewOwner"
  ): TypedContractMethod<
    [_newOwnerCandidate: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "replaceGuardian"
  ): TypedContractMethod<
    [_oldGuardian: AddressLike, _newGuardian: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requiredConfirmations"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RecoveryConfirmation"
  ): TypedContractEvent<
    RecoveryConfirmationEvent.InputTuple,
    RecoveryConfirmationEvent.OutputTuple,
    RecoveryConfirmationEvent.OutputObject
  >;
  getEvent(
    key: "RecoveryExecuted"
  ): TypedContractEvent<
    RecoveryExecutedEvent.InputTuple,
    RecoveryExecutedEvent.OutputTuple,
    RecoveryExecutedEvent.OutputObject
  >;
  getEvent(
    key: "RecoveryNomination"
  ): TypedContractEvent<
    RecoveryNominationEvent.InputTuple,
    RecoveryNominationEvent.OutputTuple,
    RecoveryNominationEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RecoveryConfirmation(address)": TypedContractEvent<
      RecoveryConfirmationEvent.InputTuple,
      RecoveryConfirmationEvent.OutputTuple,
      RecoveryConfirmationEvent.OutputObject
    >;
    RecoveryConfirmation: TypedContractEvent<
      RecoveryConfirmationEvent.InputTuple,
      RecoveryConfirmationEvent.OutputTuple,
      RecoveryConfirmationEvent.OutputObject
    >;

    "RecoveryExecuted(address,address)": TypedContractEvent<
      RecoveryExecutedEvent.InputTuple,
      RecoveryExecutedEvent.OutputTuple,
      RecoveryExecutedEvent.OutputObject
    >;
    RecoveryExecuted: TypedContractEvent<
      RecoveryExecutedEvent.InputTuple,
      RecoveryExecutedEvent.OutputTuple,
      RecoveryExecutedEvent.OutputObject
    >;

    "RecoveryNomination(address)": TypedContractEvent<
      RecoveryNominationEvent.InputTuple,
      RecoveryNominationEvent.OutputTuple,
      RecoveryNominationEvent.OutputObject
    >;
    RecoveryNomination: TypedContractEvent<
      RecoveryNominationEvent.InputTuple,
      RecoveryNominationEvent.OutputTuple,
      RecoveryNominationEvent.OutputObject
    >;
  };
}
