/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IRRStablecoin__factory } from "./IRRStablecoin__factory";
export { IRedemptionService__factory } from "./IRedemptionService__factory";
