/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRedemptionService,
  IRedemptionServiceInterface,
} from "../../../../src/contracts/IRRStablecoin.sol/IRedemptionService";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "requestRedemption",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRedemptionService__factory {
  static readonly abi = _abi;
  static createInterface(): IRedemptionServiceInterface {
    return new Interface(_abi) as IRedemptionServiceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRedemptionService {
    return new Contract(address, _abi, runner) as unknown as IRedemptionService;
  }
}
